@startuml
!include <c4/C4_Context.puml>  

title Glass Wall Download Context Overview

Person(client, Client, "A client for the glasswall")

System(glasswall, "GlassWall CDR", "deep-File Inspection, Remediation and Sanitisation")
System(website, "glasswall.com", "glass wall website")

Rel_Down(client, glasswall, "Download Files Request", 1)

Rel(glasswall, website, "Download Files Request", 2)
Rel_Back(glasswall, website, "Requested Files", 3)

Rel_Back(client, glasswall, "Santizied Files", 4)

@enduml
