apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: minio
  namespace: argo-events
spec:
  minio:
    example:
      endpoint: play.min.io
      insecure: true
      accessKey:
        key: accesskey
        name: my-s3-credentials
      secretKey:
        key: secretkey
        name: my-s3-credentials
      bucket:
        name: yarden
      events:
        - s3:ObjectCreated:Put
  template:
    metadata: {}
